### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by savonov** [savonov/practice#1]
Current schema

![image](https://user-images.githubusercontent.com/44122945/51347184-158e8380-1aa8-11e9-8186-aa446abbd190.png)

**Comment by savonov** [comment]
![image](https://user-images.githubusercontent.com/44122945/51178674-0652de80-18cc-11e9-94c0-93cb083f436a.png)

**Comment by savonov** [comment]
[postgres.txt](https://github.com/savonov/practice/files/2759499/postgres.txt)

**Comment by savonov** [comment]
![image](https://user-images.githubusercontent.com/44122945/51181643-5d5cb180-18d4-11e9-981f-9a535d603de9.png)

**Comment by savonov** [comment]
[post.txt](https://github.com/savonov/practice/files/2759681/post.txt)

**Comment by MiraculousNightingale** [comment]
![image](https://user-images.githubusercontent.com/34477181/51182251-38693e00-18d6-11e9-814b-10decc50aca3.png)

**Comment by MiraculousNightingale** [comment]
![image](https://user-images.githubusercontent.com/34477181/51345742-64d2b500-1aa4-11e9-9552-b9b20aa0e3b8.png)

Updated schema

**Comment by nightingale262** [comment]
![image](https://user-images.githubusercontent.com/34477181/52053790-fd683b00-2562-11e9-9d8e-aaa5db6215db.png)
